export const bookFilterableFields = [
    "searchTerm",
    "author",
    "genre",
    "publishedAt",
    "title",
];
export const bookGenres = [
    "Action",
    "Fantasy",
    "Science Fiction",
    "Mystery",
    "Romance",
    "Historical Fiction",
    "Horror",
    "Thriller/Suspense",
    "Comedy/Humor",
    "Biography/Autobiography",
    "Drama",
    "Young Adult",
    "Crime/Noir",
    "Adventure",
    "Poetry",
    "Self-help",
    "Satire",
    "Western",
    "Paranormal/Supernatural",
    "Graphic Novel/Comic",
    "Education",
];
